services:
  - type: web
    name: syllabus-management-system
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python setup.py
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_DEBUG
        value: false
    healthCheckPath: /health
    autoDeploy: true 